version: "3.8"

services:
  elementum:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "3000:80"
    restart: unless-stopped
    container_name: elementum-app
